# Generated by Django 5.2.10 on 2026-02-07 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user_agent',
        ),
    ]
