# Generated by Django 5.2.10 on 2026-02-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_remove_image_ip_address_remove_image_user_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('total_count', models.PositiveIntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'trash_counter',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
