# Generated by Django 5.2.10 on 2026-02-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_trashcounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
