# Generated by Django 5.2.10 on 2026-02-21 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0005_image_added_to_dataset_image_assigned_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='splits',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='DatasetClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('introduced_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_classes', to='classifier.datasetversion')),
            ],
            options={
                'db_table': 'dataset_classes',
                'ordering': ['name'],
            },
        ),
    ]
