# Generated by Django 5.2.10 on 2026-02-21 10:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0006_datasetversion_splits_datasetclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasetclass',
            options={'ordering': ['name'], 'verbose_name': 'Dataset class', 'verbose_name_plural': 'Dataset classes'},
        ),
        migrations.AlterModelOptions(
            name='datasetversion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Dataset version', 'verbose_name_plural': 'Dataset versions'},
        ),
        migrations.AlterModelOptions(
            name='trashcounter',
            options={'ordering': ['-recorded_at'], 'verbose_name': 'Trash counter', 'verbose_name_plural': 'Trash counters'},
        ),
        migrations.AlterField(
            model_name='datasetclass',
            name='introduced_in',
            field=models.ForeignKey(blank=True, help_text='Version that first introduced this class.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='introduced_classes', to='classifier.datasetversion'),
        ),
        migrations.AlterField(
            model_name='datasetclass',
            name='name',
            field=models.CharField(help_text='Canonical class label (e.g. "Plastic").', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='name',
            field=models.CharField(help_text='Unique version identifier, e.g. "v1".', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AlterField(
            model_name='datasetversion',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The parent version this was forked from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='classifier.datasetversion'),
        ),
        migrations.AlterField(
            model_name='image',
            name='added_to_dataset',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='all_predictions',
            field=models.JSONField(blank=True, help_text='Raw inference output: {"logits": [...], "energy": float}.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='assigned_label',
            field=models.CharField(blank=True, db_index=True, help_text='Operator-assigned class label.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Size in bytes.', null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(help_text='Original upload filename.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='reviewed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='image',
            name='top_prediction',
            field=models.CharField(blank=True, db_index=True, help_text='Predicted class (NULL for OOD images).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trashcounter',
            name='class_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='trashcounter',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['top_prediction', 'reviewed', '-uploaded_at'], name='idx_image_ood_review'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['assigned_label', 'added_to_dataset'], name='idx_image_staging'),
        ),
    ]
