# Generated by Django 5.2.10 on 2026-02-23 15:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0007_alter_datasetclass_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physical_path', models.CharField(help_text='Relative path to the image file from project root.', max_length=500)),
                ('split', models.CharField(blank=True, db_index=True, default='', help_text='Logical split (e.g. "dataset_train"). Blank for flat layouts.', max_length=50)),
                ('class_label', models.CharField(db_index=True, help_text='Class label (folder name or operator-assigned).', max_length=150)),
                ('filename', models.CharField(help_text='Image basename for display.', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size of the physical file in bytes.')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_image', models.ForeignKey(blank=True, help_text='The OOD Image record this entry originated from (NULL for seed data).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='version_entries', to='classifier.image')),
                ('version', models.ForeignKey(help_text='The dataset version this entry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='classifier.datasetversion')),
            ],
            options={
                'verbose_name': 'Version entry',
                'verbose_name_plural': 'Version entries',
                'db_table': 'version_entries',
                'ordering': ['class_label', 'filename'],
                'indexes': [models.Index(fields=['version', 'split', 'class_label'], name='idx_ve_version_split_class'), models.Index(fields=['version', 'class_label'], name='idx_ve_version_class')],
                'constraints': [models.UniqueConstraint(fields=('version', 'physical_path'), name='uq_ve_version_path')],
            },
        ),
    ]
