# Generated by Django 5.2.10 on 2026-02-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0008_versionentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasetversion',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this is the active version for training.'),
        ),
    ]
