# Generated by Django 5.2.10 on 2026-02-23 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0009_datasetversion_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_name', models.CharField(db_index=True, help_text='Unique run identifier, e.g. "model_v2_20260224_143052".', max_length=200, unique=True)),
                ('dataset_version_name', models.CharField(db_index=True, help_text='Name of the dataset version used for training.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('training', 'Training'), ('evaluating', 'Evaluating'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Full training config snapshot (JSON).')),
                ('num_classes', models.PositiveIntegerField(blank=True, null=True)),
                ('num_train_samples', models.PositiveIntegerField(blank=True, null=True)),
                ('num_val_samples', models.PositiveIntegerField(blank=True, null=True)),
                ('num_test_samples', models.PositiveIntegerField(blank=True, null=True)),
                ('epochs_completed', models.PositiveIntegerField(default=0)),
                ('test_accuracy', models.FloatField(blank=True, null=True)),
                ('test_f1', models.FloatField(blank=True, null=True)),
                ('metrics_summary', models.JSONField(blank=True, default=dict, help_text='Top-level evaluation metrics (accuracy, F1, etc.).')),
                ('comparison', models.JSONField(blank=True, default=dict, help_text='Comparison with previous model (deltas + recommendation).')),
                ('model_path', models.CharField(blank=True, default='', help_text='Path to the saved .keras model file.', max_length=500)),
                ('is_active_model', models.BooleanField(db_index=True, default=False, help_text='Whether this model is currently serving live inference.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Training run',
                'verbose_name_plural': 'Training runs',
                'db_table': 'training_runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
