# Generated by Django 5.2.10 on 2026-04-10 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0010_trainingrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Setting key (e.g., 'media_root')", max_length=100, unique=True)),
                ('value', models.TextField(help_text="Setting value (e.g., '/path/to/folder')")),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Setting',
                'verbose_name_plural': 'App Settings',
            },
        ),
    ]
