# Generated by Django 5.2.10 on 2026-04-20 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0011_appsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_id', models.CharField(db_index=True, help_text='Unique identifier string sent by the edge device.', max_length=100)),
                ('last_active', models.DateTimeField(auto_now=True, help_text='Last time this bin communicated with the server.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(help_text='The edge user this bin belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='bins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bin',
                'verbose_name_plural': 'Bins',
                'db_table': 'bins',
                'ordering': ['-last_active'],
                'unique_together': {('user', 'bin_id')},
            },
        ),
        migrations.CreateModel(
            name='TrashItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(db_index=True, max_length=100)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('bin', models.ForeignKey(blank=True, help_text='The bin that detected this item (null for manual uploads).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trash_items', to='classifier.bin')),
            ],
            options={
                'verbose_name': 'Trash item event',
                'verbose_name_plural': 'Trash item events',
                'db_table': 'trash_items',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.DeleteModel(
            name='TrashCounter',
        ),
        migrations.AddField(
            model_name='image',
            name='bin',
            field=models.ForeignKey(blank=True, help_text='The edge bin that captured this OOD image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ood_images', to='classifier.bin'),
        ),
        migrations.AddIndex(
            model_name='trashitem',
            index=models.Index(fields=['class_name', 'recorded_at'], name='trash_items_class_n_d6815b_idx'),
        ),
    ]
