# Generated by Django 5.2.10 on 2026-04-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0012_bin_trashitem_image_bin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_tag', models.CharField(help_text='e.g., v2.1', max_length=50, unique=True)),
                ('b2_file_key', models.CharField(help_text='Path in Backblaze B2 (e.g., models/v2.1.keras)', max_length=500)),
                ('checksum', models.CharField(help_text='SHA256 checksum to verify download integrity.', max_length=128)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this is the recommended version for Edge sites.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cloud_model_releases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edge_site_id', models.CharField(db_index=True, help_text='The source site ID (e.g., NY_Facility_1)', max_length=100)),
                ('b2_file_key', models.CharField(help_text='Path in Backblaze B2 (e.g., incoming/ny1/img_99.jpg)', max_length=500)),
                ('label', models.CharField(help_text='The operator-assigned label from the Edge site.', max_length=100)),
                ('is_ready_for_master', models.BooleanField(db_index=True, default=False, help_text='True once the file upload to B2 is confirmed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cloud_pending_images',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='is_synced_to_cloud',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this labeled OOD image has been pushed to the cloud broker.'),
        ),
    ]
