# Generated by Django 5.2.10 on 2026-08-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0013_modelrelease_pendingimage_image_is_synced_to_cloud'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='idx_image_staging',
        ),
    ]
