# Generated by Django 5.2.10 on 2026-08-03 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0014_remove_image_idx_image_staging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='dataset_version',
        ),
        migrations.RemoveField(
            model_name='image',
            name='added_to_dataset',
        ),
        migrations.DeleteModel(
            name='TrainingRun',
        ),
        migrations.DeleteModel(
            name='VersionEntry',
        ),
        migrations.DeleteModel(
            name='DatasetClass',
        ),
        migrations.DeleteModel(
            name='DatasetVersion',
        ),
    ]

