"""
Django settings for wastex project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (if it exists)
# We set override=False so that terminal environment variables (like SITE_ROLE) 
# take precedence over the .env file.
load_dotenv(BASE_DIR / '.env', override=False)

# ── Site Configuration ──────────────────────────────────────────────────────
# Roles: EDGE (on-site), MASTER (Paris training), CLOUD (Broker)
SITE_ROLE = os.getenv('SITE_ROLE', 'EDGE').upper().strip()
if SITE_ROLE not in ('EDGE', 'MASTER', 'CLOUD'):
    raise ImproperlyConfigured(f"Invalid SITE_ROLE: {SITE_ROLE}")

# Separate session cookies for each role to prevent browser conflicts
SESSION_COOKIE_NAME = f'sessionid_{SITE_ROLE.lower()}'



# ── Security ─────────────────────────────────────────────────────────────────
# All secrets MUST be provided via .env — no insecure fallbacks.

SECRET_KEY = os.getenv('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY is not set. Add it to your .env file.\n"
        "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(50))\""
    )

DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Comma-separated list of allowed hosts, e.g. "localhost,192.168.1.10"
_allowed_hosts_env = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,.onrender.com')
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]

# Allow POST requests (like login) from network IP
CSRF_TRUSTED_ORIGINS = [
    'http://192.169.0.109:8000',
    'http://192.169.0.109:8001',
    'http://10.187.246.77:8000',
    'http://10.187.246.77:8001',
    'http://10.205.102.77:8000',
    'http://10.205.102.77:8001',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'classifier',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wastex.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wastex.wsgi.application'


# Database configuration
# ─────────────────────────────────────────────────────────────────────────────
import dj_database_url

DATABASE_URL = os.getenv('DATABASE_URL')

if SITE_ROLE == 'CLOUD' and DATABASE_URL:
    # Production Cloud Role (Supabase)
    DATABASES = {
        'default': dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            ssl_require=True if os.getenv('DB_SSL_MODE') == 'require' else False
        )
    }
else:
    # Edge/Master Local Role (Isolated SQLite)
    # This prevents the Master from seeing Edge data directly on the same machine.
    db_name = f'db_{SITE_ROLE.lower()}.sqlite3'
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / db_name,
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# ── Storage Configuration ────────────────────────────────────────────────
# Each role gets its own root folder to ensure strict isolation.
STORAGE_BASE = BASE_DIR / 'storage' / SITE_ROLE.lower()

def get_storage_path(env_key: str, default_path: Path) -> Path:
    """Get storage path from environment or use default role-based path."""
    env_value = os.getenv(env_key)
    if env_value:
        return Path(env_value)
    return default_path

# Trained Models (ML model checkpoints)
MODELS_ROOT = get_storage_path('WASTE_MODELS_ROOT', STORAGE_BASE / 'models')

# Media & Datasets
MEDIA_ROOT = get_storage_path('WASTE_MEDIA_ROOT', STORAGE_BASE / 'media')
DATASETS_ROOT = get_storage_path('WASTE_DATASETS_ROOT', STORAGE_BASE / 'datasets')

# Backblaze B2 (S3 Compatible) - Available to all roles for authenticated sync
AWS_ACCESS_KEY_ID = os.getenv('B2_APPLICATION_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('B2_APPLICATION_KEY')
AWS_STORAGE_BUCKET_NAME = os.getenv('B2_BUCKET_NAME')
AWS_S3_ENDPOINT_URL = os.getenv('B2_ENDPOINT')
AWS_S3_REGION_NAME = os.getenv('B2_REGION', 'us-east-005')

if SITE_ROLE == 'CLOUD':
    # Cloud Broker configuration (Backblaze B2)
    
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
        },
    }
    
    MEDIA_URL = f'{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/'
else:
    # Local Edge node configuration
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
    MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_REDIRECT_URL = '/'

# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
LOGOUT_REDIRECT_URL = '/accounts/login/'
